// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeriodicElements.Models;

namespace PeriodicElements.Migrations
{
    [DbContext(typeof(PeriodicElementsContext))]
    partial class PeriodicElementsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("PeriodicElements.Models.Element", b =>
                {
                    b.Property<int>("AtomicNumber")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AtomicMass");

                    b.Property<string>("AtomicRadius");

                    b.Property<string>("BoilingPoint");

                    b.Property<string>("BondingType");

                    b.Property<string>("ElectronConfiguration");

                    b.Property<string>("FirstIonisationEnergy");

                    b.Property<string>("GroupBlock");

                    b.Property<string>("MeltingPoint");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Symbol")
                        .IsRequired();

                    b.Property<int>("X_Position");

                    b.Property<int>("Y_Position");

                    b.HasKey("AtomicNumber");

                    b.ToTable("Element");
                });
#pragma warning restore 612, 618
        }
    }
}
