// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MobileInfoAPI.Models;

namespace MobileInfoAPI.Migrations
{
    [DbContext(typeof(MobileInfoAPIContext))]
    [Migration("20190725061118_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("MobileInfoAPI.Models.MobileSpecs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BatteryRating");

                    b.Property<string>("Company");

                    b.Property<string>("ModelName");

                    b.Property<string>("ModelNumber");

                    b.Property<double>("PhoneLength");

                    b.Property<double>("PhoneWidth");

                    b.Property<string>("Processor");

                    b.Property<double>("ScreenLength");

                    b.Property<double>("ScreenWidth");

                    b.HasKey("Id");

                    b.ToTable("MobileSpecs");
                });
#pragma warning restore 612, 618
        }
    }
}
